name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Display Go version
        run: go version

      - name: Run make fmt
        run: make fmt

      - name: Run make mocks
        run: make mocks

      - name: Run make build
        run: make build

      - name: Run make test
        run: make test
